### ISSUE TITLE
Without the M0 Express board

### ISSUE THREAD

**Issue by Miahbird** [robmarkcole/HASS-circuitpython-air-quality-sensor-node#1]
This is a question regarding if I'm not able to procure an Metro M0 Express board, can I use the Raspberry pi for homeassistant OS as well as for calling the PMS sensor? and if without the board can we use the arduino as an alternative? @robmarkcole

**Comment by robmarkcole** [comment]
PMS board is compatible with any of those yes. Checkout https://github.com/robmarkcole/rpi-enviro-mqtt

**Comment by Miahbird** [comment]
> PMS board is compatible with any of those yes. Checkout https://github.com/robmarkcole/rpi-enviro-mqtt

can I use the Raspberry pi for homeassistant OS as well as for calling the PMS sensor though at the same time?

**Comment by robmarkcole** [comment]
Don't think so

**Comment by daneesteva** [comment]
> Don't think so

I am trying to detect air quality using the pms5003 to the home assistant though the serial_pm platform has a problem on Homeassistant, can I run homeassistant whilst the sensors are connected and still using your code? 

I am just making a simple IOT based air quality detection for my house. Thanks for the help in advance

**Comment by robmarkcole** [comment]
You can install home assistant on the same RPi, install into raspbian OS. This is turning into home assistant support not specific to this codebase so please move conversation to home assistant forum
